"""add_previous_price_and_change_date_to_products

Revision ID: 0fd2767ace7a  # <<< ใส่ Revision ID ของไฟล์นี้ (ที่ Alembic สร้างให้)
Revises: dfdc6de8397a     # <<< !!! สำคัญ: ใส่ Revision ID ของ HEAD ก่อนหน้าไฟล์นี้ !!!
Create Date: 2025-05-15 16:00:00.000000 # <<< วันเวลาโดยประมาณที่คุณสร้างไฟล์นี้

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0fd2767ace7a'  # <<< ใส่ Revision ID ของไฟล์นี้ (ต้องตรงกับด้านบน)
down_revision: Union[str, None] = 'dfdc6de8397a' # <<< !!! สำคัญ: ใส่ Revision ID ของ HEAD ก่อนหน้าไฟล์นี้ !!!

branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # print("Adding column: products.previous_price_b2c") # ลบออก
    # op.add_column('products', sa.Column('previous_price_b2c', sa.Float(), nullable=True)) # ลบออก
    
    # print("Adding column: products.price_b2c_last_changed") # ลบออก
    # op.add_column('products', sa.Column('price_b2c_last_changed', sa.DateTime(timezone=True), nullable=True)) # ลบออก
    # ### end Alembic commands ###
    # print("Columns previous_price_b2c and price_b2c_last_changed already added by dfdc6de8397a.")
    pass # หรืออาจจะมีคำสั่ง upgrade อื่นๆ ที่ไม่เกี่ยวข้องกับคอลัมน์ซ้ำซ้อน


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # print("Dropping column: products.price_b2c_last_changed") # ลบออก
    # op.drop_column('products', 'price_b2c_last_changed') # ลบออก
    
    # print("Dropping column: products.previous_price_b2c") # ลบออก
    # op.drop_column('products', 'previous_price_b2c') # ลบออก
    # ### end Alembic commands ###
    # print("Columns previous_price_b2c and price_b2c_last_changed are handled by dfdc6de8397a downgrade.")
    pass # หรืออาจจะมีคำสั่ง downgrade อื่นๆ ที่ไม่เกี่ยวข้อง