"""ปรับปรุง Product model เพิ่ม standard_cost, price_b2c, price_b2b

Revision ID: 30a6368179e3
Revises: 
Create Date: 2025-05-06 04:10:41.200381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30a6368179e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('standard_cost', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('price_b2c', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('products', sa.Column('price_b2b', sa.Float(), nullable=True))
    op.drop_column('products', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('products', 'price_b2b')
    op.drop_column('products', 'price_b2c')
    op.drop_column('products', 'standard_cost')
    # ### end Alembic commands ###
