"""Add discount_percent to Location model

Revision ID: 3474951829be
Revises: 22c33ac37810
Create Date: 2025-05-06 23:42:11.330676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3474951829be'
down_revision: Union[str, None] = '22c33ac37810'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('discount_percent', sa.Float(), nullable=True))
    op.add_column('sale_items', sa.Column('original_unit_price', sa.Float(), nullable=True))
    op.add_column('sale_items', sa.Column('discount_amount', sa.Float(), nullable=True))
    op.add_column('sale_items', sa.Column('is_rtc', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale_items', 'is_rtc')
    op.drop_column('sale_items', 'discount_amount')
    op.drop_column('sale_items', 'original_unit_price')
    op.drop_column('locations', 'discount_percent')
    # ### end Alembic commands ###
