"""add_barcode_column_to_products_table

Revision ID: <your_new_revision_id>
Revises: <id_of_previous_migration> 
Create Date: <timestamp>

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a7d69b8f0a2' # ใส่ Revision ID ของไฟล์นี้
down_revision: Union[str, None] = '321b883110ba'
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('barcode', sa.String(), nullable=True))
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=True) # หรือ unique=False ตามที่คุณตัดสินใจ
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.drop_column('products', 'barcode')
    # ### end Alembic commands ###